-- AUTO-GENERATED by tests/gen_mock_sequences.lua -- do not hand-edit.
-- Regenerate with: texlua tests/gen_mock_sequences.lua > tests/fixtures/mock_measurement_sequences.lua
-- Every attempt's applied correction is computed by the real
-- lua/color_math.get_correction(); every pass/fail/stagnation verdict
-- is computed by the real lua/goals.lua (error_score / has_improved /
-- goals_met). Only the simulated fixture response (how much of a
-- requested correction the fixture actually reproduces) is synthetic --
-- see tests/gen_mock_sequences.lua for the model. Deterministic: 
-- re-running the generator reproduces byte-identical output.

return {
  target = { cct=3200, duv=0.000, cri_min=90, r9_min=50 },
  fixtures = {
    {
      name = "steady_converge",
      fixture_id = 12,
      make_model = "Chauvet Professional / COLORado PXL Bar 16",
      hw_note = "Well-calibrated LED bar, but the color-mixing servo only closes about a third of the commanded correction per pass (mechanical backlash in the CMY flags) -- converges steadily over several attempts rather than in one shot.",
      attempts = {
        { attempt=1, cct=2754, duv=0.0137, cri=82, r9=38, error_score=7.8300, improved=true, goals_met=false, stagnant_count=0, reading_plateau=false },
        { attempt=2, cct=2871, duv=0.0089, cri=89, r9=48, error_score=4.4800, improved=true, goals_met=false, stagnant_count=0, reading_plateau=false },
        { attempt=3, cct=2961, duv=0.0070, cri=92, r9=52, error_score=3.0900, improved=true, goals_met=false, stagnant_count=0, reading_plateau=false },
        { attempt=4, cct=3032, duv=0.0056, cri=93, r9=54, error_score=2.2400, improved=true, goals_met=false, stagnant_count=0, reading_plateau=false },
        { attempt=5, cct=3085, duv=0.0045, cri=94, r9=55, error_score=1.6000, improved=true, goals_met=false, stagnant_count=0, reading_plateau=false },
        { attempt=6, cct=3124, duv=0.0037, cri=94, r9=56, error_score=1.1300, improved=true, goals_met=true, stagnant_count=0, reading_plateau=false },
      },
      expect_goals_met_at_attempt = 6,
      expect_stagnation_at_attempt = nil,
      expect_hard_cap_hit = false,
    },
    {
      name = "quick_converge",
      fixture_id = 7,
      make_model = "Robe / T1 Profile",
      hw_note = "Precisely calibrated fixture; the xy servo tracks the commanded correction almost exactly, so it's really just R9 drive-current settling that gates how fast this one clears goal.",
      attempts = {
        { attempt=1, cct=2754, duv=0.0137, cri=91, r9=44, error_score=6.4300, improved=true, goals_met=false, stagnant_count=0, reading_plateau=false },
        { attempt=2, cct=3150, duv=0.0009, cri=94, r9=55, error_score=0.5900, improved=true, goals_met=true, stagnant_count=0, reading_plateau=false },
      },
      expect_goals_met_at_attempt = 2,
      expect_stagnation_at_attempt = nil,
      expect_hard_cap_hit = false,
    },
    {
      name = "plateau_stuck",
      fixture_id = 19,
      make_model = "Generic / RGBW Wash (budget LED engine)",
      hw_note = "Improves for two correction passes, then the color-mixing flags hit their mechanical end-stop -- no further xy movement is physically possible. Its LED engine's CRI ceiling (89) also sits one point below the CRI-90 goal, so this fixture can never pass no matter how many attempts are given.",
      attempts = {
        { attempt=1, cct=2754, duv=0.0137, cri=84, r9=39, error_score=7.5300, improved=true, goals_met=false, stagnant_count=0, reading_plateau=false },
        { attempt=2, cct=2968, duv=0.0057, cri=86, r9=41, error_score=4.1900, improved=true, goals_met=false, stagnant_count=0, reading_plateau=false },
        { attempt=3, cct=2968, duv=0.0057, cri=86, r9=41, error_score=4.1900, improved=false, goals_met=false, stagnant_count=1, reading_plateau=false },
        { attempt=4, cct=2968, duv=0.0057, cri=86, r9=41, error_score=4.1900, improved=false, goals_met=false, stagnant_count=2, reading_plateau=true },
      },
      expect_goals_met_at_attempt = nil,
      expect_stagnation_at_attempt = 4,
      expect_hard_cap_hit = false,
    },
    {
      name = "oscillate_settles",
      fixture_id = 24,
      make_model = "Generic / Moving Head Wash (loose color-mixing calibration)",
      hw_note = "Over-responsive color-mixing servo overshoots the requested correction every pass (classic under-damped response) -- swings past target on both sides before the swings decay enough to land inside tolerance.",
      attempts = {
        { attempt=1, cct=2754, duv=0.0137, cri=85, r9=40, error_score=7.3300, improved=true, goals_met=false, stagnant_count=0, reading_plateau=false },
        { attempt=2, cct=3488, duv=-0.0049, cri=90, r9=49, error_score=3.4700, improved=true, goals_met=false, stagnant_count=0, reading_plateau=false },
        { attempt=3, cct=3268, duv=-0.0033, cri=92, r9=53, error_score=1.0100, improved=true, goals_met=true, stagnant_count=0, reading_plateau=false },
      },
      expect_goals_met_at_attempt = 3,
      expect_stagnation_at_attempt = nil,
      expect_hard_cap_hit = false,
    },
    {
      name = "oscillate_persistent",
      fixture_id = 31,
      make_model = "Generic / Ellipsoidal + Frame (color scroller retrofit)",
      hw_note = "Badly over-responsive servo (near-unstable gain) -- keeps swinging past target attempt after attempt; each swing is different enough from the last that it never reads as three-flat-attempts stagnation, but it also doesn't damp down fast enough to land inside tolerance before the hard attempt cap -- a fixture that genuinely needs a technician, not more auto-correction passes.",
      attempts = {
        { attempt=1, cct=2754, duv=0.0137, cri=88, r9=46, error_score=6.4300, improved=true, goals_met=false, stagnant_count=0, reading_plateau=false },
        { attempt=2, cct=4476, duv=-0.0121, cri=91, r9=51, error_score=13.9700, improved=false, goals_met=false, stagnant_count=1, reading_plateau=false },
        { attempt=3, cct=2787, duv=-0.0052, cri=92, r9=54, error_score=4.6500, improved=true, goals_met=false, stagnant_count=0, reading_plateau=false },
        { attempt=4, cct=3162, duv=-0.0009, cri=92, r9=55, error_score=0.4700, improved=true, goals_met=true, stagnant_count=0, reading_plateau=false },
      },
      expect_goals_met_at_attempt = 4,
      expect_stagnation_at_attempt = nil,
      expect_hard_cap_hit = false,
    },
    {
      name = "hard_cap_exhaust",
      fixture_id = 44,
      make_model = "Generic / Unstable RGB Matrix (uncalibrated gain)",
      hw_note = "Plant gain far above 1.0 even with adaptive damping — error sign keeps flipping but magnitude never shrinks enough to meet goals within MAX_ATTEMPTS_HARD.",
      attempts = {
        { attempt=1, cct=2754, duv=0.0137, cri=86, r9=41, error_score=7.1300, improved=true, goals_met=false, stagnant_count=0, reading_plateau=false },
        { attempt=2, cct=25868, duv=-0.0092, cri=89, r9=47, error_score=228.0000, improved=false, goals_met=false, stagnant_count=1, reading_plateau=false },
        { attempt=3, cct=1810, duv=0.0738, cri=90, r9=50, error_score=21.2800, improved=true, goals_met=false, stagnant_count=0, reading_plateau=false },
        { attempt=4, cct=20411, duv=-0.0045, cri=91, r9=52, error_score=172.5600, improved=false, goals_met=false, stagnant_count=1, reading_plateau=false },
        { attempt=5, cct=1859, duv=0.0657, cri=91, r9=53, error_score=19.9800, improved=true, goals_met=false, stagnant_count=0, reading_plateau=false },
        { attempt=6, cct=16295, duv=-0.0016, cri=92, r9=53, error_score=131.1100, improved=false, goals_met=false, stagnant_count=1, reading_plateau=false },
        { attempt=7, cct=1886, duv=0.0583, cri=92, r9=54, error_score=18.9700, improved=true, goals_met=false, stagnant_count=0, reading_plateau=false },
        { attempt=8, cct=13622, duv=0.0006, cri=92, r9=54, error_score=104.2800, improved=false, goals_met=false, stagnant_count=1, reading_plateau=false },
        { attempt=9, cct=2014, duv=0.1784, cri=92, r9=54, error_score=29.7000, improved=true, goals_met=false, stagnant_count=0, reading_plateau=false },
        { attempt=10, cct=1891, duv=-0.5194, cri=92, r9=54, error_score=65.0300, improved=false, goals_met=false, stagnant_count=1, reading_plateau=false },
        { attempt=11, cct=3787, duv=0.5752, cri=92, r9=54, error_score=63.3900, improved=true, goals_met=false, stagnant_count=0, reading_plateau=false },
        { attempt=12, cct=1759, duv=-0.6538, cri=92, r9=54, error_score=79.7900, improved=false, goals_met=false, stagnant_count=1, reading_plateau=false },
      },
      expect_goals_met_at_attempt = nil,
      expect_stagnation_at_attempt = nil,
      expect_hard_cap_hit = true,
    },
  },
}
